# Reference: https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: label-microservice
build:
  artifacts:
  - image: gcr.io/issue-label-bot-dev/bot-worker
    # Set the context to the root directory. 
    # All paths in the Dockerfile should be relative to this one.
    context: ..
    # Automatically sync python files to the container. This should avoid
    # the need to rebuild and redeploy when the files change.
    # TODO(https://github.com/GoogleContainerTools/skaffold/issues/3448): We use manual sync
    # because inferred sync doesn't work
    #
    # This only works if we autorestart the program on changes.
    #
    # Important: Make sure you current context has the namespace
    # set to the namespace where your pods are deployed otherwise
    # the sync doesn't appear to work.
    sync:
        manual:
        - src: 'py/code_intelligence/*.py'
          dest: '/'
        - src: 'py/label_microservice/*.py'
          dest: '/'
    kaniko:
      dockerfile: Label_Microservice/deployment/Dockerfile.worker
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env: 
        # TODO(GoogleContainerTools/skaffold#3468) skaffold doesn't
        # appear to work with workload identity
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/user-gcp-sa.json
      cache: {}
  - image: gcr.io/issue-label-bot-dev/labelbot-diff
    # Set the context to the go directory
    # All paths in the dockerfile should be relative to this
    context: ./go
    kaniko:
      # Relative to context
      dockerfile: Dockerfile.automl
      buildContext:
        gcsBucket: issue-label-bot-dev_skaffold-kaniko
      env: 
        # TODO(GoogleContainerTools/skaffold#3468) skaffold doesn't
        # appear to work with workload identity
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/user-gcp-sa.json 
      cache: {}
  cluster:    
    pullSecretName: user-gcp-sa
    # Build in the kaniko namespace because we need to disable ISTIO sidecar injection
    # see  GoogleContainerTools/skaffold#3442
    namespace: kaniko
    resources:
      requests:
        cpu: 8
        memory: 16Gi

deploy:
  kustomize:
    path: deployment/overlays/dev