apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: labelbot-diff
  name: labelbot-diff
  namespace: label-bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labelbot-diff
  template:
    metadata:
      labels:
        app: labelbot-diff
    spec:
      containers:
      - command:
        - /automl
        - serve
        - --kptFile=/src/code-intelligence.git/Label_Microservice/deployment/Kptfile
        - --port=8080
        - --retrainInterval=24h
        image: gcr.io/issue-label-bot-dev/labelbot-diff:3697618-dirty@sha256:2b7e759153baacf59514c98e50cb01eec0fc7aa2d7e2b271ac0a3c5cc516a74d
        name: diff
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /src
          name: src
      - args:
        - --repo=https://github.com/kubeflow/code-intelligence.git
        - --branch=master
        - --root=/src
        - --wait=30
        image: k8s.gcr.io/git-sync:v3.1.6
        name: sync
        volumeMounts:
        - mountPath: /src
          name: src
      serviceAccount: auto-update
      volumes:
      - emptyDir: {}
        name: src
