apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: issue-label-bot-user@issue-label-bot-dev.iam.gserviceaccount.com
  name: auto-update
  namespace: label-bot-prod
secrets:
- name: label-bot-ssh
- name: label-bot-cd-github-private-key
