apiVersion: v1
data:
  model_config.yaml: |-
    # This file describes the models to load
    orgs:
      - name: kubeflow
        automl_model: "projects/976279526634/locations/us-central1/models/TCN654213816573231104"
kind: ConfigMap
metadata:
  labels:
    app: label-bot
    environment: prod
    service: label-bot
  name: label-bot-model-config-7fdmtg95kc
  namespace: label-bot-prod
