apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: worker
spec:
    replicas: 5
    template:
      metadata:
        labels:
          app: worker          
      spec:
        volumes:
        - name: google-cloud-key
          secret:
            secretName: user-gcp-sa
        - name: github-app
          secret:
            secretName: github-app
        containers:
        - name: app
          image: gcr.io/issue-label-bot-dev/bot-worker
          command: 
            - python3
            - -m 
            - label_microservice.worker
            - subscribe_from_env
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"                      
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: github-app
              mountPath: /var/secrets/github
          env:
            - name: PORT
              value: "80"
            # This should be the name of the in-cluster K8s service running issue embeddings
            - name: ISSUE_EMBEDDING_SERVICE
              value: "http://issue-embedding-server"
            - name: PROJECT
              value: issue-label-bot-dev
            #- name: PROJECT_ID
            #  valueFrom:
            #    secretKeyRef:
            #      name: ml-app-inference-secret
            #      key: PROJECT_ID
            #- name: GCP_PROJECT_ID
            #  valueFrom:
            #    secretKeyRef:
            #      name: ml-app-inference-secret
            #      key: GCP_PROJECT_ID
            #- name: GH_ISSUE_API_KEY
            #  valueFrom:
            #    secretKeyRef:
            #      name: ml-app-inference-secret
            #      key: GH_ISSUE_API_KEY
            # APP_ID and APP_URL identify the GitHub OAuth app            
            # TODO(jlewi): Why do we load this from a secret? Why not
            # just store the value here?
            - name: APP_ID
              valueFrom:
               secretKeyRef:
                 name: ml-app-inference-secret
                 key: APP_ID
            # TODO(jlewi): Why do we load this from a secret? Why not
            # just store the value here?
            - name: APP_URL
              valueFrom:
               secretKeyRef:
                 name: ml-app-inference-secret
                 key: APP_URL
            # PRIVATE_KEY is the key for the GitHub OAuth App
            #- name: PRIVATE_KEY
            #  valueFrom:
            #   secretKeyRef:
            #     name: ml-app-inference-secret
            #     key: PRIVATE_KEY
            #- name: WEBHOOK_SECRET
            #  valueFrom:
            #    secretKeyRef:
            #      name: ml-app-inference-secret
            #      key: WEBHOOK_SECRET            
            - name: GITHUB_APP_PEM_KEY
              value: /var/secrets/github/kf-label-bot-dev.private-key.pem
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/user-gcp-sa.json
        restartPolicy: Always
