apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: label-bot-
commonLabels:
  service: label-bot
  app: label-bot
images:
- name: gcr.io/issue-label-bot-dev/bot-worker
  newName: gcr.io/issue-label-bot-dev/bot-worker
resources:
  - service.yaml
  - deployments.yaml
configMapGenerator:
  - name: model-config
    files:
      - configs/model_config.yaml