apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  # Use a single replica for development
  replicas: 1
  template:
    spec:
      containers:
      - name: app
        # We use the wrapper program run_with_auto_restart.
        # This will autorestart the program whenever we detect code changes.
        # We use this to pick up changes to the code from skaffold.
        command:
        - python3
        - -m
        - code_intelligence.run_with_auto_restart
        - --directory=/py
        - --
        - python3
        - -m
        - label_microservice.worker
        - subscribe_from_env
        env:
        - name: PROJECT
          value: issue-label-bot-dev
        - name: ISSUE_EVENT_TOPIC
          value: "TEST_event_queue"
        - name: ISSUE_EVENT_SUBSCRIPTION
          value: "label_bot_dev"
        - # The values for the Kubeflow kf-label-bot-dev application
          # See kubeflow/code-intelligence#84
          name: GITHUB_APP_ID
          value: "50112"
        - name: GITHUB_APP_PEM_KEY
          value: /var/secrets/github/kf-label-bot-dev.private-key.pem
        - # Flask environment variables
          # Enable debug mode to trigger automatic reloading when code changes
          name: FLASK_DEBUG
          value: "true"
        - name: FLASK_ENVIRONMENT
          value: "development"
