apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service-account.yaml
images:
- digest: sha256:9a93e576825c65b1062424869ce93d47d90fed9117891dd95e31eeb57e878a90
  name: gcr.io/issue-label-bot-dev/labelbot-diff
  newName: gcr.io/issue-label-bot-dev/labelbot-diff:63789ef
