apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service-account.yaml
images:
- digest: sha256:32ecb5f829796b37fb5b5ddc2c3d98c693a81728b285fa90756f2b4b8f1075ae
  name: gcr.io/issue-label-bot-dev/labelbot-diff
  newName: gcr.io/issue-label-bot-dev/labelbot-diff:874d2f5-dirty
