apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mlbot-net
  namespace: mlapp
spec:
  acme:
    config:
    - domains:
      - mlbot.net
      http01:
        ingress: mlbot-net
  commonName: mlbot.net
  dnsNames:
  - mlbot.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: mlapp-tls
