apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: predict-mlapp-tls
  namespace: mlapp
spec:
  acme:
    config:
    - domains:
      - predict.mlbot.net
      http01:
        ingress: ml-gh-app
  commonName: predict.mlbot.net
  dnsNames:
  - predict.mlbot.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: predict-mlapp-tls
