apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:      
    app: mnist # {"$ref":"#/definitions/io.k8s.cli.substitutions.name"}  
  name: mnist # {"$ref":"#/definitions/io.k8s.cli.substitutions.name"}    
spec:
  # TODO(jlewi): Should we take ownership?
  addOwnerRef: false
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: kubeflow.org
    kind: Notebook
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: core
    kind: ServiceAccount
  - group: core
    kind: Service
  - group: networking.istio.io
    kind: VirtualService
  descriptor:
    description: Notebook for kubeflow code intelligence
    keywords:
    - jupyter
    - notebook    
    links:
    # TODO(jlewi): Need to annotate this with kpt setters
    - description: jupyterlab
      url: https://kf-v1-0210.endpoints.jlewi-dev.cloud.goog/notebook/kubeflow-jlewi/mnist/lab
    - description: theia
      url: https://kf-v1-0210.endpoints.jlewi-dev.cloud.goog/notebook/kubeflow-jlewi/mnist-theia/
    # The type text is what shows up in the software column in the applications dashboard.
    # It will be a link to the first in the list of links.
    # Additional links will show up in the details page.
    type: notebook
    version: v1
  # TODO(jlewi): Use commonLabels to ensure it gets applied to all resources?
  selector:
    matchLabels:     
      app: mnist # {"$ref":"#/definitions/io.k8s.cli.substitutions.name"}        