apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow-jlewi # {"$ref":"#/definitions/io.k8s.cli.substitutions.namespace"}
resources:
- application.yaml
- notebook.yaml
- pvc.yaml
- service.yaml
- virtual_service.yaml
