apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # TODO(jlewi): Need to create a kpt setter for this.
  name: workspace-mnist
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # We need more storage.
      storage: 100Gi
  storageClassName: standard
  volumeMode: Filesystem
