apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: modelsyncs.automl.cloudai.kubeflow.org
spec:
  group: automl.cloudai.kubeflow.org
  names:
    kind: ModelSync
    plural: modelsyncs
  scope: ''
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            failedPipelineRunsHistoryLimit:
              format: int32
              minimum: 0
              type: integer
            needsSyncUrl:
              type: string
            parameters:
              items:
                properties:
                  needsSyncName:
                    type: string
                  pipelineName:
                    type: string
                required:
                - needsSyncName
                - pipelineName
                type: object
              type: array
            pipelineRunTemplate:
              properties:
                json:
                  description: This should be json parseable as pipelinerun template
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
            successfulPipelineRunsHistoryLimit:
              format: int32
              minimum: 0
              type: integer
          type: object
        status:
          properties:
            active:
              items:
                properties:
                  apiVersion:
                    type: string
                  fieldPath:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  resourceVersion:
                    type: string
                  uid:
                    type: string
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: []
  storedVersions: []
