apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: worker-test
spec:
    replicas: 5
    template:
      metadata:
        labels:
          app: worker
      spec:
        volumes:
        - name: google-cloud-key
          secret:
            secretName: user-gcp-sa
        containers:
        - name: mycontainer
          image: gcr.io/issue-label-bot-dev/bot-worker-test
          command: ['python3', 'worker.py', 'subscribe', '--topic_name=TEST_event_queue', '--subscription_name=TEST_subscription_for_event_queue']
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: PROJECT_ID
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: GCP_PROJECT_ID
            - name: GH_ISSUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: GH_ISSUE_API_KEY
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: APP_ID
            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: APP_URL
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: WEBHOOK_SECRET
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: ml-app-inference-secret-test
                  key: PRIVATE_KEY
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/user-gcp-sa.json
        restartPolicy: Always
