apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: label-bot
    environment: prod
    service: label-bot
  name: label-bot-worker
  namespace: label-bot-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: label-bot
      environment: prod
      service: label-bot
  template:
    metadata:
      labels:
        app: label-bot
        environment: prod
        service: label-bot
    spec:
      containers:
      - command:
        - python3
        - -m
        - label_microservice.worker
        - subscribe_from_env
        env:
        - name: PORT
          value: "80"
        - name: ISSUE_EMBEDDING_SERVICE
          value: http://issue-embedding-server
        - name: PROJECT
          value: issue-label-bot-dev
        - name: ISSUE_EVENT_TOPIC
          value: event_queue
        - name: ISSUE_EVENT_SUBSCRIPTION
          value: label_bot_prod
        - name: GITHUB_APP_ID
          value: "27079"
        - name: GITHUB_APP_PEM_KEY
          value: /var/secrets/github/issue-label-bot-github-app.private-key.pem
        image: gcr.io/issue-label-bot-dev/bot-worker:6848ad6
        name: app
        resources:
          requests:
            cpu: "4"
            memory: 4Gi
        volumeMounts:
        - mountPath: /var/secrets/github
          name: github-app
      restartPolicy: Always
      serviceAccountName: default-editor
      volumes:
      - name: github-app
        secret:
          secretName: github-app
