apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: code-intelligence-admin@issue-label-bot-dev.iam.gserviceaccount.com
  labels:
    app: cloud-endpoints-controller
    app.kubernetes.io/component: cloud-endpoints
    app.kubernetes.io/name: cloud-endpoints
    kustomize.component: cloud-endpoints
  name: kf-admin
  namespace: kubeflow
