# permissions for end users to edit modelsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelsync-editor-role
rules:
- apiGroups:
  - automl.cloudai.kubeflow.org
  resources:
  - modelsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - automl.cloudai.kubeflow.org
  resources:
  - modelsyncs/status
  verbs:
  - get
