# permissions for end users to view modelsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelsync-viewer-role
rules:
- apiGroups:
  - automl.cloudai.kubeflow.org
  resources:
  - modelsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - automl.cloudai.kubeflow.org
  resources:
  - modelsyncs/status
  verbs:
  - get
