apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: prod
namespace: label-bot-prod
patchesStrategicMerge:
- deployments.yaml
resources:
- ../../base
- namespace.yaml
images:
- digest: sha256:2faaf9d94c9beba082f184790770d1d08cb06a94b1ad4a8e797033f0bccb4cf7
  name: gcr.io/issue-label-bot-dev/bot-worker
  newName: gcr.io/issue-label-bot-dev/bot-worker:f0bf8d1-dirty
