
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-automl-cloudai-kubeflow-org-v1alpha1-modelsync
  failurePolicy: Fail
  name: mmodelsync.kb.io
  rules:
  - apiGroups:
    - automl.cloudai.kubeflow.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelsyncs

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-automl-cloudai-kubeflow-org-v1alpha1-modelsync
  failurePolicy: Fail
  name: vmodelsync.kb.io
  rules:
  - apiGroups:
    - automl.cloudai.kubeflow.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modelsyncs
