apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-github-issuefeat
  labels:
    app: ml-github-issuefeat
spec:
  replicas: 9
  selector:
    matchLabels:
      app: ml-github-issuefeat
  template:
    metadata:
      labels:
        app: ml-github-issuefeat
    spec:
      containers:
      - name: ml-github-issuefeat
        image: gcr.io/issue-label-bot-dev/issue-embedding
        command: ["python", "app.py"]
        workingDir: /flask_app
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        env:
        # TODO(jlewi): Can we get rid of this? I think this was the OAuth id but I'm not sure we need
        # that if the app is no longer talking to GitHub.
        #- name: APP_ID
        #  valueFrom:
        #    secretKeyRef:
        #      name: ml-github-issuefeat-secret
        #      key: APP_ID
        - name: FLASK_ENV
          value: production
        - name: PORT
          value: '80'
        - name: authors
          value: 'f'
        ports:
        - containerPort: 80