apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: issue-embedding-
commonLabels:
  app: issue-embedding
images:
- name: gcr.io/issue-label-bot-dev/issue-embedding
  newName: gcr.io/issue-label-bot-dev/issue-embedding
resources:
  - service.yaml
  - deployments.yaml
