apiVersion: v1
kind: Service
metadata:
  name: ml-github-issuefeat
  labels:
    app: ml-github-issuefeat
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ml-github-issuefeat